# Version.cmake
#
# Embed build version information into C++ target.
#
# Provides:
#   - Project version
#   - Git version
#   - Build information
#
# Usage:
#   target_enable_version(<target>)

cmake_minimum_required(VERSION 3.21)

#
# Query Git information
#
function(_version_query_git source_dir)

    set(VERSION_GIT_TAG "unknown")
    set(VERSION_GIT_COMMIT "unknown")
    set(VERSION_GIT_DIRTY "")

    find_program(GIT_EXECUTABLE git)

    if (GIT_EXECUTABLE AND EXISTS "${source_dir}/.git")
        execute_process(
                COMMAND ${GIT_EXECUTABLE} describe --tags --abbrev=0
                WORKING_DIRECTORY ${source_dir}
                OUTPUT_VARIABLE VERSION_GIT_TAG
                OUTPUT_STRIP_TRAILING_WHITESPACE
                ERROR_QUIET
        )

        execute_process(
                COMMAND ${GIT_EXECUTABLE} rev-parse --short HEAD
                WORKING_DIRECTORY ${source_dir}
                OUTPUT_VARIABLE VERSION_GIT_COMMIT
                OUTPUT_STRIP_TRAILING_WHITESPACE
                ERROR_QUIET
        )

        execute_process(
                COMMAND ${GIT_EXECUTABLE} diff --quiet
                WORKING_DIRECTORY ${source_dir}
                RESULT_VARIABLE git_diff_result
                ERROR_QUIET
        )

        execute_process(
                COMMAND ${GIT_EXECUTABLE} diff --cached --quiet
                WORKING_DIRECTORY ${source_dir}
                RESULT_VARIABLE git_cached_diff_result
                ERROR_QUIET
        )

        if (NOT git_diff_result EQUAL 0
                OR NOT git_cached_diff_result EQUAL 0)
            set(VERSION_GIT_DIRTY "-dirty")
        endif ()
    endif ()

    set(VERSION_GIT_TAG
            "${VERSION_GIT_TAG}"
            PARENT_SCOPE)
    set(VERSION_GIT_COMMIT
            "${VERSION_GIT_COMMIT}"
            PARENT_SCOPE)
    set(VERSION_GIT_DIRTY
            "${VERSION_GIT_DIRTY}"
            PARENT_SCOPE)
endfunction()

#
# Generate version.h
#
function(_version_generate_header output_dir)

    file(MAKE_DIRECTORY ${output_dir})

    set(version_header
            "${output_dir}/version.h")

    file(WRITE ${version_header}
            "#pragma once

// This file is generated by CMake.
// DO NOT MODIFY MANUALLY.

namespace version
{

inline const char* GetVersion() noexcept
{
    return \"${PROJECT_VERSION}\";
}

inline const char* GetGitVersion() noexcept
{
    return \"${VERSION_GIT_TAG}-${VERSION_GIT_COMMIT}${VERSION_GIT_DIRTY}\";
}

inline const char* GetBuildInfo() noexcept
{
    return
        __DATE__
        \" \"
        __TIME__
        \" \"
        \"${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}\"
        \" \"
        \"${CMAKE_SYSTEM_NAME} ${CMAKE_SYSTEM_PROCESSOR}\";
}

} // namespace version
")

endfunction()

#
# Enable version information for target
#
function(target_enable_version target)

    if (NOT TARGET ${target})
        message(FATAL_ERROR
                "target_enable_version: target '${target}' does not exist")
    endif ()

    set(version_output_dir
            "${CMAKE_CURRENT_BINARY_DIR}/generated/version")

    #
    # Query git information
    #
    _version_query_git(
            "${CMAKE_SOURCE_DIR}"
    )

    #
    # Generate version.h
    #
    _version_generate_header(
            "${version_output_dir}"
    )

    #
    # Add include path
    #
    target_include_directories(
            ${target}
            PRIVATE
            "${version_output_dir}"
    )

    #
    # Reconfigure when git state changes
    #
    set(git_head
            "${CMAKE_SOURCE_DIR}/.git/HEAD")
    set(git_index
            "${CMAKE_SOURCE_DIR}/.git/index")

    if (EXISTS ${git_head})
        set_property(
                DIRECTORY APPEND PROPERTY
                CMAKE_CONFIGURE_DEPENDS
                ${git_head}
        )
    endif ()

    if (EXISTS ${git_index})
        set_property(
                DIRECTORY APPEND PROPERTY
                CMAKE_CONFIGURE_DEPENDS
                ${git_index}
        )
    endif ()

    message(STATUS
            "Version enabled for target: ${target}")
    message(STATUS
            "Project version: ${PROJECT_VERSION}")
    message(STATUS
            "Git version: ${VERSION_GIT_TAG}-${VERSION_GIT_COMMIT}${VERSION_GIT_DIRTY}")

endfunction()
